# #####################################################################
# Automatically generated by qmake (2.01a) ?? 4? 12 13:25:25 2013
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c \
    interface.c
HEADERS += cmd_type.h \
    interface.h \
    ipnc.h
